### PR TITLE
Makefile as per suggestions by others

### PR DESCRIPTION
**Pull request by vmurali**
@JasonGross @gmalecha @samuelgruetter Does this work for you guys? It seems to work for me, and it automatically picks up vernacular files that are added into subdirectories.

### CODE REVIEW

**Comment by JasonGross** [comment]
This will fail in confusing ways if you ever `rm` a `.v` file as your only change.  Also, I am a bit concerned about the use of `shell find` rather than `git ls-files`.

**Comment by vmurali** [comment]
Agree with removing a `.v` file. Not sure why you are concerned about `shell find`.

**Comment by vmurali** [comment]
Now make gives a better error if a .v file is removed. I experimented with both git ls-files and find, and I found find to be better based on my workflow. I want make to work on all the local files I have as opposed to what I have checked in.

**Comment by JasonGross** [comment]
> doesn't that mean that it's better to use find than git ls-files?

What do you mean?  If I have a file `foo.v` lying around that has a non-terminating comment, then using `find` will make it impossible to use `make` on anything at all, because `coqdep` will barf on the syntax error in the file that is just lying around.

> I want make to work on all the local files I have as opposed to what I have checked in.

I'm curious about this.  Is it that you want to be able to hijack the bbv makefile to make `.v` files that are completely unrelated, or you want to be able to run `make` without having to run `git add` first, or something else?  (Note that you don't need to have a file committed for `git ls-files` to find it; you just need to have run `git add` on it.)

**Comment by vmurali** [comment]
I would like to test a new file before even doing a git add. That is
because I never do a git add, and instead combine it using git commit -a. I
don't type make unless my current directory is clean, whereas I suppose you
keep only the staged version clean.

**Comment by JasonGross** [comment]
Note that I don't actually do much (if any) development in this repo, so feel free to disregard my preferences.

**Comment by samuelgruetter** [comment]
I think it's interesting to learn about everybody's preferences of build systems, and see different trade offs :wink: 

Sorry for the delay in my reaction (I was at FLoC & vacation).

I like this Makefile a lot, and there wasn't major objection, so I'm merging it. Thanks @vmurali!

**Pull request merged**
