### PR TITLE
Adapt w.r.t. coq/coq#16004.

### PR DESCRIPTION
**Pull request by ppedrot**
Should be backwards compatible.

### CODE REVIEW

**Comment by JasonGross** [comment]
This is not backwards compatible because `Hint Rewrite` did not support `Global` in 8.8, which Fiat Crypto legacy still supports.  Is there a fix that is backwards compatible all the way to 8.7?

**Comment by ppedrot** [comment]
I am afraid not...

**Comment by JasonGross** [comment]
Why can't this error be turned back into a warning or suppressed by command-line flags?

**Comment by JasonGross** [comment]
Can we just disable the warning instead?  And fix the imports when we need to in the future

**Comment by ppedrot** [comment]
I basically disagree with the disabling of warning. This is just hiding the problem, and it will explode at our face as soon as we switch the semantics of the default locality attribute of hints. I'd rather postpone the switch and / or apply political pressure on the devs that both want to be in the CI while retaining a broad backwards compatibility spectrum.

**Comment by JasonGross** [comment]
> it will explode at our face as soon as we switch the semantics of the default locality attribute of hints. I'd rather [...] apply political pressure on the devs that both want to be in the CI while retaining a broad backwards compatibility spectrum.

Would you be satisfied with a PR that had all of our developments that disable the warning also pass `-set 'Loose Hint Behavior "Strict"'` on the command line (or otherwise set it in the relevant places)?  If I understand correctly, this will make the developments compatible with switching the default behavior from Global to Export, right?

**Comment by ppedrot** [comment]
@JasonGross that's better than nothing, but it will require a lot of work while still being quite brittle. But I guess I'd be fine with this first step.

**Pull request closed without merging**
